name: cloudquery

version: V2.6.0

storageClassName: local-path

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

dms:
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi