name: cloudquery

version: V2.7.0

storageClassName: ebs-gp3

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

dms:
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 2Gi

ldap:
  enable: true
  urls: ldap://ldap:389
  username: cn=admin,dc=example,dc=org
  password: admin
  base: dc=example,dc=org