apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-dms
  name: cloudquery-dms
spec:
  ports:
    - name: "http"
      port: 9001
      targetPort: 9001
    - name: "socket"
      port: 4389
      targetPort: 4389
  selector:
    app: cloudquery-dms