apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-dms
  labels:
    app: cloudquery-dms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-dms
  template:
    metadata:
      labels:
        app: cloudquery-dms
    spec:
      containers:
        - name: dms
          image: yshanchui/cloudquery-dms:cloudquery-club-{{ .Values.version }}
          env:
            - name: LANG
              value: C.UTF-8
            - name: LC_ALL
              value: C.UTF-8
            - name: _JAVA_OPTIONS
              value: -Xmx1600m -Xms1600m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.dms.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-dms
  name: cloudquery-dms
spec:
  ports:
    - name: "http"
      port: 9001
      targetPort: 9001
    - name: "socket"
      port: 4389
      targetPort: 4389
  selector:
    app: cloudquery-dms