apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-dms-configmap
data:
  application.yml: |
    profiles: prod
    # 指定服务启动端口
    server:
      tomcat:
        max-http-form-post-size: -1
      port: 9001
      error:
        include-exception: false
        include-stacktrace: always
      servlet:
        context-path: /dms
    file_system:
      data_change: /opt/cloudquery/DataChange
    # 定义日志级别
    logging:
      level:
        root: info
    # 定义dm module 路径
    dms:
      server_home: /opt/cloudquery/dmc/dms_home
      module_directory: /opt/cloudquery/dmc/modules
      stg: /opt/cloudquery/dmc/modules
    # 连接失效时间 单位：分钟
    connection:
      expired_time: 40
      destroy_time: 45
      number_limit: 40
    statement:
      execute:
        timeout: 5 # minute
    spring:
      cloud:
        zookeeper:
          connect-string: cloudquery-zookeeper:2181
      
      application:
        name: cloudquery-dms
      cache:
        type: redis
      redis:
        database: 1
        host: cloudquery-redis-master
        port: 6379
        password: nya6X#uSes@
        timeout: 5000
        mq:
          producer:
            retries: 1
            expired-time: 300000
            queue-size: 2000
          consumer:
            pull-time-out: 1
            batch-size: 1
            auto-ack: true
            no-ack-time-out: 300000
            offset-strategy: last_consumed
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
      swagger:
        enable: true
    
    #######导出文件路径#######
    task:
      home: ${CLOUDQUERY_HOME:/opt/cloudquery/data}
    #################################################dubbo的配置#####################################################
    dubbo:
      scan:
        base-packages: cn.bintools.cloudquery.dms
    
      application:
        id: cloudquery-dms
        name: cloudquery-dms
        qos-port: 33336
        qos-enable: true
        qos-accept-foreign-ip: false
      protocol:
        id: dms
        name: dubbo
        port: 12366
        payload: 100971520
        serialization: kryo
    
    
      registry:
        id: cloudquery-dmsProd
        address: zookeeper://cloudquery-zookeeper:2181
      consumer:
        timeout: 300000
        group: cloudquery_test1
        check: false
    
    springdoc:
      api-docs:
        enabled: false
      swagger-ui:
        enabled: false