apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-export
  labels:
    app: cloudquery-export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-export
  template:
    metadata:
      labels:
        app: cloudquery-export
    spec:
      containers:
        - name: export
          image: yshanchui/cloudquery-export:cloudquery-club-{{ .Values.version }}
          env:
            - name: CLOUDQUERY_HOME
              value: /opt/cloudquery/data
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-export
  name: cloudquery-export
spec:
  ports:
    - name: "http"
      port: 8787
      targetPort: 8787
    - name: "sokcet"
      port: 9803
      targetPort: 9803
  selector:
    app: cloudquery-export