apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-export
  name: cloudquery-export
spec:
  ports:
    - name: "http"
      port: 8787
      targetPort: 8787
    - name: "sokcet"
      port: 9803
      targetPort: 9803
  selector:
    app: cloudquery-export