apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-export-configmap
data:
  application.yml: |
    # 指定服务启动端口
    server:
      port: 8787
      error:
        include-exception: false
        include-stacktrace: always
      servlet:
        context-path: /export
    # 定义日志级别
    logging:
      level:
        root: info
    # 定义dm module 路径
    export:
      server_home: /opt/cloudquery/dmc/dms_home
      module_directory: /opt/cloudquery/dmc/modules
      stg: /opt/cloudquery/dmc/modules
    file_system:
      base_dir: ${task.home}
      user_data:  ${task.home}/userData
      user_cache_data: ${task.home}/userCacheData
    # 连接失效时间 单位：分钟
    connection:
      expired_time: 40
      destroy_time: 45
      number_limit: 40
    statement:
      execute:
        timeout: 5 # minute
    spring:
      main:
        allow-circular-references: true
      profiles:
        active: prod
    
    
      application:
        name: cloudquery-exportProd
      cache:
        type: redis
      redis:
        database: 1
        host: {{ .Values.redis.addr }}
        port: 6379
        password: nya6X#uSes@
        timeout: 5000
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
      swagger:
        enable: true
      datasource:
        url: jdbc:postgresql://cloudquery-postgresql:5432/postgres
        username: postgres
        password: WVCmFZs841@
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
            jdbc:
              lob:
                non_contextual_creation: true
        open-in-view: true
      servlet:
        multipart:
          file-size-threshold: 4MB # 超过1MB multipart数据将写入本地文件
          enabled: true
          max-file-size: 100MB # 文件最大大小
          max-request-size: 101MB # multipart 最大请求
    
    
    #######导出文件路径#######
    task:
      home: ${CLOUDQUERY_HOME:/opt/cloudquery/data}
      core-pool-size: 3
      maximum-pool-size: 10
      keep-alive-time: 60 # 分钟
      queue-size: 500
      schedule:
        period: 1 # 分钟 定时去任务表中取排队任务
        dead-task: 01:00:00 #死任务阈值，超过这个时间就将运行任务设置失败
    
    # 文件存储路径
    task-center:
      file-path: ${CLOUDQUERY_HOME:/opt/cloudquery/data}
    cloudquery:
      home: ${CLOUDQUERY_HOME:/opt/cloudquery/data}
    dump:
      oracle:
        file-path: /opt/dump/oracle
      sqlserver:
        file-path: /opt/dump/sqlserver
    #################################################dubbo的配置#####################################################
    dubbo:
      scan:
        base-packages: cn.bintools.cloudquery.export
    
      application:
        id: cloudquery-export
        name: cloudquery-export
        qos-port: 33336
        qos-enable: true
        qos-accept-foreign-ip: false
      protocol:
        id: export
        name: dubbo
        port: 22367
        payload: 100971520
        serialization: kryo
    
    
      registry:
        id: cloudquery-exportProd
        address: zookeeper://cloudquery-zookeeper:2181
      consumer:
        timeout: 300000
        group: cloudquery_test1
        check: false
    
    springdoc:
      api-docs:
        enabled: false
      swagger-ui:
        enabled: false
