apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-debug
  labels:
    app: cloudquery-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-debug
  template:
    metadata:
      labels:
        app: cloudquery-debug
    spec:
      containers:
        - name: cloudquery-debug
          image: yshanchui/cloudquery-debug:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-debug
  name: cloudquery-debug
spec:
  ports:
    - name: "http"
      port: 8899
      targetPort: 8899
  selector:
    app: cloudquery-debug