apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-debug
  name: cloudquery-debug
spec:
  ports:
    - name: "http"
      port: 8899
      targetPort: 8899
  selector:
    app: cloudquery-debug