apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-web
  name: enterprise-web
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 9898
  selector:
    app: enterprise-web