apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-web
  labels:
    app: enterprise-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-web
  template:
    metadata:
      labels:
        app: enterprise-web
    spec:
      containers:
        - image: yshanchui/cloudquery-base-web:cloudquery-club-{{ .Values.version }}
          name: enterprise-web
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 9898
            - containerPort: 9999
          volumeMounts:
            - name: enterprise-web-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: enterprise-web-nginx-conf
          configMap:
            name: enterprise-web-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-web
  name: enterprise-web
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 9898
  selector:
    app: enterprise-web