apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-gateway
  name: cloudquery-gateway
spec:
  ports:
    - name: "http"
      port: 8888
      targetPort: 8888
  selector:
    app: cloudquery-gateway