apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-gateway
  labels:
    app: cloudquery-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-gateway
  template:
    metadata:
      labels:
        app: cloudquery-gateway
    spec:
      containers:
        - name: cloudquery-gateway
          image: yshanchui/cloudquery-gateway:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-gateway
  name: cloudquery-gateway
spec:
  ports:
    - name: "http"
      port: 8888
      targetPort: 8888
  selector:
    app: cloudquery-gateway