apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-flow
  name: cloudquery-flow
spec:
  ports:
    - name: "http"
      port: 9876
      targetPort: 9876
  selector:
    app: cloudquery-flow