apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-flow
  labels:
    app: cloudquery-flow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-flow
  template:
    metadata:
      labels:
        app: cloudquery-flow
    spec:
      containers:
        - name: cloudquery-flow
          image: yshanchui/cloudquery-flow:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-flow
  name: cloudquery-flow
spec:
  ports:
    - name: "http"
      port: 9876
      targetPort: 9876
  selector:
    app: cloudquery-flow