apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-metadict
  labels:
    app: cloudquery-metadict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-metadict
  template:
    metadata:
      labels:
        app: cloudquery-metadict
    spec:
      containers:
        - name: cloudquery-metadict
          image: yshanchui/cloudquery-metadict:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-metadict
  name: cloudquery-metadict
spec:
  ports:
    - name: "http"
      port: 9192
      targetPort: 9192
  selector:
    app: cloudquery-metadict