apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-metadict
  name: cloudquery-metadict
spec:
  ports:
    - name: "http"
      port: 9192
      targetPort: 9192
  selector:
    app: cloudquery-metadict