apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-desens
  labels:
    app: cloudquery-desens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-desens
  template:
    metadata:
      labels:
        app: cloudquery-desens
    spec:
      containers:
        - name: cloudquery-desens
          image: yshanchui/cloudquery-desens:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/cloudquery/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: cloudquery-desens-configmap
