apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-desens
  labels:
    app: cloudquery-desens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-desens
  template:
    metadata:
      labels:
        app: cloudquery-desens
    spec:
      containers:
        - name: cloudquery-desens
          image: yshanchui/cloudquery-desens:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-desens
  name: cloudquery-desens
spec:
  ports:
    - name: "http"
      port: 6202
      targetPort: 6202
  selector:
    app: cloudquery-desens