apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-desens-configmap
data:
  application.yml: |
    profiles: prod
    # 指定服务启动端口
    server:
      port: 6202
      error:
        include-exception: false
        include-stacktrace: always
      servlet:
        context-path: /desens
    # 定义日志级别
    logging:
      level:
        cn.bintools.cloudquery.desens: info
        cn.bintools.common.cm: error
        cn.bintools.cloudquery.protocol.aop: error
    #数据库配置
    spring:
      main:
        allow-circular-references: true
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
          location: ${java.io.tmpdir}
    
      application:
        name: cloudquery-desensProd
      jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
      redis:
        database: 1
        host: cloudquery-redis-master
        port: 6379
        password: nya6X#uSes@
        timeout: 5000
      datasource:
        url: jdbc:postgresql://cloudquery-postgresql:5432/postgres
        username: postgres
        password: WVCmFZs841@
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 20
          data-source-properties:
            cachePrepStmts: true
            cacheResultSetMetadata: true
            cacheServerConfiguration: true
            elideSetAutoCommits: true
            maintainTimeStats: false
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            rewriteBatchedStatements: true
            useLocalSessionState: true
            useServerPrepStmts: true
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            jdbc:
              lob:
                non_contextual_creation: true
      swagger:
        enable: true
    #################################################dubbo的配置#####################################################
    dubbo:
      scan:
        base-packages: cn.bintools.cloudquery.desens
    
      application:
        id: cloudquery-desens
        name: cloudquery-desens
        qos-port: 33336
        qos-enable: true
        qos-accept-foreign-ip: false
      protocol:
        id: desens
        name: dubbo
        port: 12367
        payload: 20971520
        serialization: kryo
    
    
      registry:
        id: zookeeper
        address: zookeeper://cloudquery-zookeeper:2181
      consumer:
        timeout: 300000
        group: cloudquery_test1
        check: false
    
    desens:
      # 定义dm module 路径
      server_home: /opt/cloudquery/dmc/dms_home
      module_directory: /opt/cloudquery/dmc/modules
      stg: /opt/cloudquery/dmc/modules
    
    springdoc:
      api-docs:
        enabled: false
      swagger-ui:
        enabled: false