apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudquery-analyze-archive
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi