apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-analyze
  name: cloudquery-analyze
spec:
  ports:
    - name: "http"
      port: 9007
      targetPort: 9007
  selector:
    app: cloudquery-analyze