apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-analyze
  labels:
    app: cloudquery-analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-analyze
  template:
    metadata:
      labels:
        app: cloudquery-analyze
    spec:
      containers:
        - name: cloudquery-analyze
          image: yshanchui/cloudquery-analyze:cloudquery-club-{{ .Values.version }}
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx800m -Xms800m
          volumeMounts:
            - name: config-volume
              mountPath: /opt/cloudquery/config
#            - name: archive-volume
#              mountPath: /opt/cloudquery/archive
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: cloudquery-analyze-configmap
            items:
              - key: application.yml
                path: application.yml
              - key: spring-context.xml
                path: spring-context.xml
              - key: sql.properties
                path: sql.properties
#        - name: archive-volume
#          persistentVolumeClaim:
#            claimName: cloudquery-analyze-archive
