apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-message
  name: cloudquery-message
spec:
  ports:
    - name: "http"
      port: 8899
      targetPort: 8899
    - name: "socket"
      port: 7090
      targetPort: 7090
  selector:
    app: cloudquery-message