apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-message-configmap
data:
  application.yml: |
    profiles: dev
    # 指定服务启动端口
    server:
      port: 8899
      error:
        include-exception: false
        include-stacktrace: always
      servlet:
        context-path: /message

    # 定义日志级别
    logging:
      level:
        cn.bintools.cloudquery.message: error

    #数据库配置
    spring:
      main:
        allow-circular-references: true



      application:
        name: cloudquery-message
      cloud:
        zookeeper:
          connect-string: cloudquery-zookeeper:2181
      redis:
        timeout: 5000
        database: 1
        host: {{ .Values.redis.addr }}
        port: 6379
        password: nya6X#uSes@
      datasource:
        url: jdbc:postgresql://cloudquery-postgresql:5432/postgres
        username: postgres
        password: WVCmFZs841@
        driver-class-name: org.postgresql.Driver
        #    data: classpath:init.sql
        #    sql-script-encoding: utf-8
        #    initialization-mode: ALWAYS
      task:
        execution:
          pool:
            max-size: 256
            queue-capacity: 256
            core-size: 64
      jpa:
        show-sql: true
        open-in-view: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            enable_lazy_load_no_trans: true
            jdbc:
              lob:
                non_contextual_creation: true
      swagger:
        enable: true
    #################################################dubbo的配置#####################################################
    dubbo:
      scan:
        base-packages: cn.bintools.cloudquery.message
      application:
        id: cloudquery-message
        name: cloudquery-message
        qos-port: 33334
        qos-enable: true
        qos-accept-foreign-ip: false
      protocol:
        id: message
        name: dubbo
        port: 12346


      registry:
        id: zookeeper-message
        address: zookeeper://cloudquery-zookeeper:2181
      consumer:
        timeout: 30000
        group: cloudquery_test1
        check: false

    #################################################socket的配置#####################################################
    socket:
      hostName: 0.0.0.0
      port: 7090
      # 服务端Client标识
      keypropertis: session
      # 服务端失败重试次数
      failretrycount: 10
      baseEvent: baseEvent
      sendEvent: sendEvent
      # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
      maxFramePayloadLength: 1048576
      # 设置http交互最大内容长度
      maxHttpContentLength: 1048576
      # socket连接数大小（如只监听一个端口boss线程组为1即可）
      bossCount: 1
      workCount: 5000
      allowCustomRequests: true
      # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
      upgradeTimeout: 1000000
      # Ping消息超时时间（毫秒），默认6秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
      pingTimeout: 60000
      # Ping消息间隔（毫秒），默认5秒。客户端向服务器发送一条心跳消息间隔
      pingInterval: 5000

    springdoc:
      api-docs:
        enabled: false
      swagger-ui:
        enabled: false
