apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-message
  labels:
    app: cloudquery-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-message
  template:
    metadata:
      labels:
        app: cloudquery-message
    spec:
      containers:
        - name: message
          image: yshanchui/cloudquery-message:cloudquery-club-V2.3.0
          env:
            - name: _JAVA_OPTIONS
              value: -Xmx1g -Xms1g
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1500Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/cloudquery/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: cloudquery-message-configmap
