apiVersion: v1
kind: Service
metadata:
  name: cloudquery-redis
  namespace: cloudquery
spec:
  ports:
    - name: tcp-redis
      protocol: TCP
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: cloudquery
    app.kubernetes.io/name: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cloudquery-clickhouse
  namespace: cloudquery
spec:
  selector:
    app: cloudquery-clickhouse
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8123
      targetPort: 8123
    - protocol: TCP
      name: tcp
      port: 9000
      targetPort: 9000