apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-terminal
  name: cloudquery-terminal
spec:
  ports:
    - name: "http"
      port: 9950
      targetPort: 9950
  selector:
    app: cloudquery-terminal