apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudquery-terminal
  labels:
    app: cloudquery-terminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudquery-terminal
  template:
    metadata:
      labels:
        app: cloudquery-terminal
    spec:
      containers:
        - name: cloudquery-terminal
          image: yshanchui/cloudquery-base-terminal:cloudquery-club-{{ .Values.version }}
          command: ["sh", "-c"]
          args:
            - "/opt/cloudquery/terminal -p 9950 -w -ws-origin .* --audit-url http://cloudquery-analyze:9007/analyze/extract/extract_log"
          env:
            - name: CLOUDQUERY_HOME
              value: /opt/cloudquery/data
            - name: TZ
              value: Asia/Shanghai
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudquery-terminal
  name: cloudquery-terminal
spec:
  ports:
    - name: "http"
      port: 9950
      targetPort: 9950
  selector:
    app: cloudquery-terminal
