apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudquery-user-configmap
data:
  application.yml: |
    spring:
      main:
        allow-circular-references: true
      cloud:
        zookeeper:
          connect-string: cloudquery-zookeeper:2181
      application:
        name: cloudquery-user

      jackson:
        time-zone: GMT+8
      profiles:
        active: prod
      redis:
        timeout: 5000
        database: 1
        host: {{ .Values.redis.addr }}
        port: 6379
        password: nya6X#uSes@
      datasource:
        url: jdbc:postgresql://cloudquery-postgresql:5432/postgres
        username: postgres
        password: WVCmFZs841@
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
        properties:
          javax:
            persistence:
              validation:
                mode: none
          hibernate:
            enable_lazy_load_no_trans: true
            jdbc:
              lob:
                non_contextual_creation: true
        open-in-view: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      servlet:
        multipart:
          max-file-size: 400MB
          max-request-size: 1024MB
      swagger:
        enable: true

    server:
      servlet:
        context-path: /user
      port: 8001
      error:
        include-exception: false
        include-stacktrace: always
    # 定义日志级别
    logging:
      level:
        cn.bintools.cloudquery: info
        com.bintools.permissionmiddleware: error
    user:
      server_home: /opt/cloudquery/dmc/dms_home
      module_directory: /opt/cloudquery/dmc/modules
      images: /work/JK_WorkSpace/一键打包_前端后端审计_base-2.4.4.1开始_ARM_X86_全部加密_企业版社区版/5/cloudquery-base2/cloudquery-user/ignore/images
      avatars:
        dir: /opt/cloudquery/avatars
        extname: jpg,png
      #权限缓存超时时间，单位秒
      permission_cache_timeout: 36000
      #显示行过滤权限
      show_row_filter_permission: false
      #权限模板数量
      permission_template_limit: 20
      #权限模板可启用数量
      permission_enable_template_limit: 10
      # 通信加密算法，支持 RSA，SM2，若不配置，默认是 RSA
      # transmission_algorithm: RSA
      # 存储加密算法，支持 DES、AES，若不配置，默认是 DES
      # storage_algorithm: DES
      # 存储加密密钥，若不配置，使用系统默认密钥，DES默认密钥：XZFnM2rwkJg8qsKmBYIQauHS  AES默认密钥：BlztWtMNhtNHUZNv0wIUzw==
      # storage_algorithm_key: XZFnM2rwkJg8qsKmBYIQauHS
    #login.limit 没有定义时默认为0，不限制单个账号登录会话数。 当login.limit > 0时才限制单个账号登录会话数。
    #  login:
    #    limit: 0
    sms:
      host: localhost:8080/post

    cloudquery:
      home: ${CLOUDQUERY_HOME:/opt/cloudquery/data}
      system:
        company-name: bintools
        watermark: true
        copy: false
        tab-max: 10
        file-max: 20
    #######################################################################################################################
    dubbo:
      scan:
        base-packages: cn.bintools.cloudquery.user
      application:
        id: cloudquery-uc
        name: cloudquery-uc
      protocol:
        id: uc
        name: dubbo
        port: 12345
        payload: 20971520


      registry:
        id: zookeeper-userRelease
        address: zookeeper://cloudquery-zookeeper:2181
      consumer:
        timeout: 300000
        group: cloudquery_test1
        check: false
    #监控
    monitor:
      echost: http://cloudquery-prometheus:8080
      host: cloudquery-prometheus
      port: 3000
      user: root
      password: Hello123$
      fsd-port: 9092

    springdoc:
      api-docs:
        enabled: false
      swagger-ui:
        enabled: false

    #短信网关配置
    SmsGateway:
      type: TestDemo